name: Checkout repo and upload to s3 bucket

on:
  push:
    branches:
    - master # or main after October 2020

jobs:
  build:
    name: Checkout repo and upload assets to S3 bucket. This template could be customised to build and deploy a static website (for example).

    runs-on: ubuntu-latest

    permissions:
      contents: read    # required to checkout the code from the repo
      id-token: write   # required to get JWT token from OIDC

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::<my-account-number-here>:role/github-role-to-deploy-applications
        role-session-name: github-session-deploying-<my-repo-name-here>
        aws-region: eu-west-1

    - name: Check JWT token validation was successful and that role has been assumed
      run: aws sts get-caller-identity

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy files to S3 bucket & invalidate cloudfront cache
      run: |
        aws s3 sync site/ s3://<name-of-my-s3-bucket>
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*';